services:
  unifi-threat-sync:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unifi-threat-sync
    environment:
      - UNIFI_USER=admin
      - UNIFI_PASS=password
    depends_on:
      unifi-network-application:
        condition: service_healthy
    restart: unless-stopped
      
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    volumes:
      - unifi-network-application:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  mongodb:
    image: docker.io/mongo:8
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_INITDB_ROOT_USERNAME=root #optional
      - MONGO_INITDB_ROOT_PASSWORD=password #optional
      - MONGO_INITDB_DATABASE=unifi #optional
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
    restart: unless-stopped

volumes:
  unifi-network-application:
    driver: local
  mongodb:
    driver: local

networks:
  default:
    driver: bridge
