name: ci
on:
  pull_request:
  push: { branches: [main] }

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.25.x' }

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
          args: --timeout=5m

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with: { go-version-input: '1.22' }
