name: sbom
on: [pull_request]
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Syft SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom.spdx.json }
      - name: Grype scan
        uses: anchore/scan-action@v4
        with:
          path: .
          fail-build: true
